### PR TITLE
Updated rainloop Dockerfile to build the latest stable release

### PR DESCRIPTION
**Pull request by gecgooden**

### CODE REVIEW

**Comment by lava** [comment]
Hi, thanks for the patch. I like the idea of building from a release tarball instead of cloning a random commit from git.

However, if possible I'd prefer to download a fixed version of rainloop, instead of just "latest".

If rainloop doesn't provide tarballs for specific versions I'll probably still merge this PR, because at least it will be not broken right now (I hope you tested this?), but then it seems just a matter of time until something will break again.

**Comment by gecgooden** [comment]
I couldn't find a download link for a specific version, so did latest instead.

I have tested this, and it seems to work well (I can log in, send and receive mail)

**Comment by lava** [comment]
Ok then, thanks for fixing this! :)

**Comment by gecgooden** [comment]
No worries.
For reference, this should also fix #26, #24, #20.

**Pull request merged**
