### PR TITLE
Improve docker intermediate images

### PR DESCRIPTION
**Pull request by jkliff**
- reduces RUN statements and, after apt-get usages, cleanup to reduce size of said intermediate images;
- add targets to Makefile to conveniently export images (when for example not running on same host where was built)

### CODE REVIEW

**Comment by lava** [comment]
This looks very nice, but why are you removing `/var/lib/apt/lists/*` in every Makefile? Shouldn't it be enough to do it in `mail-base`?

**Comment by jkliff** [comment]
If not removed it will be included in the overlays increasing needlessly their size. 
Arguably, the tradeoff is that one has to apt-get update again at each Dockerfile, which might increase the build time; but overlays might need to be stored, published, shared, etc, this is considered a good practice [1].

[1] https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/

**Comment by jkliff** [comment]
After re-reading your question: if not

**Comment by lava** [comment]
Ok then, thanks for contributing!

**Pull request merged**
