### PR TITLE
Updates for running build of dovecot on CoreOS Cluster or any Docker container

### PR DESCRIPTION
**Pull request by gegere**
Sorry for the 2nd pull request. I wanted to create a new branch focused on these updates as I have been updating and tweaking on the `develop` branch.

There are many updates on this branch but I wanted to try and update this repo with all our newest work and corrections.

### CODE REVIEW

**Comment by lava** [comment]
Hi after a long-distance move, a job change and a few weeks of sickness I was finally able to have a look. On a first glance, there are quite a few references to htmlgraphics.com in the source tree, it would be good if these can be removed. Also, I recommend using `git rebase -i` to produce a nicer-looking history by removing unnecessary commits and appending bugfixes directly to the relevant commit. Thirdly, I am slightly skeptical about adding fig, since I cannot support it myself, so if this is optional I would prefer to have this in a separate pull request.

Thanks for the good work!

**Comment by gegere** [comment]
Happy to see you took the time. I have no problem removing the referenced domain **htmlgraphic.com** would example.com work better? What do you think about  turning this into a environmental variable? I would like to streamline the initial process. I will be using this build(s) in dev and prod.

I can definitely rebase and clean up commits. 

**fig** is pretty awesome and not all needed but it does hurt to people who understand it so the containers can be created even faster. It does the same thing several lines in the terminal would accomplish.

Please let me know your thoughts on these as I would rather have a plan and make this even better!

**Comment by gegere** [comment]
I would like to reopen this and tomorrow I will make the first attempt at improving my past edits. Does this work for you?

**Comment by gegere** [comment]
I would like to reopen this and tomorrow I will make the first attempt at improving my past edits. Does this work for you?

**Comment by lava** [comment]
Hi, thanks for your work, but 27 commits is becoming too big for a single pull request. Also, there are still a lot of references to htmlgraphics.net in the changed files, and the patches don't apply cleanly onto master.

Can you, for each feature you would like to have in master, please do an interactive rebase onto the current master, and submit a new pull request containing only a single commit with that feature?

**Comment by gegere** [comment]
@lava this will be resolved. I will pick it apart and offer up my improvements. 

The domain htmlgraphic.com will be edited and I will start new branch for custom needs. More revisions coming soon.

**Pull request closed without merging**
